"""initial_schema

Revision ID: f3bf25f39acc
Revises: 
Create Date: 2026-09-21 13:49:11.547838
"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers used by Alembic
revision: str = 'f3bf25f39acc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ledger_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('donation_id', sa.Integer(), nullable=True),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('entry_type', sa.Enum('CREDIT', 'DEBIT', 'REFUND', name='entrytype'), nullable=False),
    sa.Column('amount_ngn', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['donation_id'], ['donations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ledger_campaign_date', 'ledger_entries', ['campaign_id', 'recorded_at'], unique=False)
    op.create_index(op.f('ix_ledger_entries_campaign_id'), 'ledger_entries', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_ledger_entries_donation_id'), 'ledger_entries', ['donation_id'], unique=True)
    op.create_index(op.f('ix_ledger_entries_recorded_at'), 'ledger_entries', ['recorded_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ledger_entries_recorded_at'), table_name='ledger_entries')
    op.drop_index(op.f('ix_ledger_entries_donation_id'), table_name='ledger_entries')
    op.drop_index(op.f('ix_ledger_entries_campaign_id'), table_name='ledger_entries')
    op.drop_index('ix_ledger_campaign_date', table_name='ledger_entries')
    op.drop_table('ledger_entries')
    # ### end Alembic commands ###
